### PR TITLE
download yawmME instead of Wii Mod Lite

### PR DESCRIPTION
**Pull request by Naim2000**
\+ C: -> %SYSTEMDRIVE%~~, literally every windows install i have has a non C drive letter it's kind of annoying~~

### CODE REVIEW

**Comment by Naim2000** [comment]
@larsenv can't have the patcher download anywhere else other than patcher.rc24.xyz so i think it's up to you, kcr won't be home for a while
also, i heard ww-43db-patcher is outdated on the server

**Comment by larsenv** [comment]
I don't want to touch his patcher.

**Comment by Naim2000** [comment]
Oh. September it is then

**Comment by KcrPL** [comment]
Do not merge for now.

**Comment by The-diam0nd** [comment]
then download it.

**Comment by Naim2000** [comment]
Yeah that's what the guide makes the user do. But that's kind of stupid, just make the patcher download it for them, just like how it's downloading WML

**Pull request closed without merging**
