### PR TITLE
download yawmME instead of WML, and download rest of apps from HBB

### PR DESCRIPTION
**Pull request by Naim2000**
haven't tested this just yet. so hang on

### CODE REVIEW

**Comment by Naim2000** [comment]
🥴 
image

**Comment by Naim2000** [comment]
(nothing)

**Comment by Naim2000** [comment]
nevermind that still says 1.5.1. kcr why did you make a release without pushing

**Comment by KcrPL** [comment]
First of all this would get rejected anyway because all the files should be hosted on our server

**Comment by Naim2000** [comment]
> First of all this would get rejected anyway because all the files should be hosted on our server

I guess my best bet is just asking larsen now

**Pull request closed without merging**
