### PR TITLE
Update RiiConnect24Patcher.sh

### PR DESCRIPTION
**Pull request by ApfelTV**
patched some cool stuff hehe

### CODE REVIEW

**Comment by ApfelTV** [comment]
thx sugar daddy

**Comment by larsenv** [comment]
Is there any specific reason why you broke up the lines?

**Comment by ApfelTV** [comment]
they wont show up right

**Comment by ApfelTV** [comment]
that `\n` is not available in bash

**Comment by larsenv** [comment]
I tried it and it worked, so I'm closing this.

**Pull request closed without merging**
