### PR TITLE
Added an comment / Use wine

### PR DESCRIPTION
**Pull request by Bildcraft1**
If the patcher uses sharpii linux / mac users must have wine as sharpii is a Windows executable

### CODE REVIEW

**Comment by Bildcraft1** [comment]
:100:

**Comment by Bildcraft1** [comment]
### :)

**Comment by Alej0hio** [comment]
The grammar isn't too great. Edit it with "Disclaimer: you're going to need to install WineHQ if you do not have that installed already.". Without cortation marks, of course.

**Comment by Bildcraft1** [comment]
I'm Italian

**Comment by Alej0hio** [comment]
I'm Norwegian

**Comment by Bildcraft1** [comment]
Modified

**Comment by Bildcraft1** [comment]
You can now run it on linux

**Comment by larsenv** [comment]
Mono is usable to patch the WADs, you say itt work when doing WAD-related things but it works fine for me.

**Pull request closed without merging**
